#spring:
# application:
#   name: Invoice_Generation_App
 # profiles:
  #  active: prod

---
spring:
  #profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Ramu@9988
    url: jdbc:mysql://localhost:3306/capstone
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
#spring.jpa.properties.hibernate.format_sql=true   
---




#spring:
 # profiles: test
  #datasource:
   # driver-class-name: org.h2.Driver
    #password: sa
    #url: jdbc:h2:mem:testdb
    #username: sa
  #h2:
   # console:
    #  enabled: true  
  #jpa:
   # database-platform: spring.config.activate.on-profile


    
